[package]
name = "convertible_macros_dev"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
convertible = {path = "../convertible/convertible", features = ["derive"]}